Wazo 2818 convert scripts python 3
wazo-platform/wazo-libsccp pull request #16
Opened 2022-12-22 21:56 UTC by DrPyser

* Convert scripts `buildh` and `utils/sccp-confgen` to python 3.
  * for `buildh` this required a custom implementation of the configparser used for the config file(to deal with duplicate option definitions), imported from wazo-confgend
* buildh: added a `-c/--config-file` switch(retaining the same default of `~/~/.wazo-libsccp-buildh-config`)
* Added type annotations
* added section on `buildh` usage to `README.md` based on information by @pc-m  

Tested both scripts successfully.

2022-12-23 13:10 UTC, pc-m requested changes

2022-12-23 13:10 UTC, pc-m commented on buildh
> +        with config_file:
what does `with config_file:` do?

2022-12-23 13:10 UTC, pc-m commented on buildh
> +    config_file = parsed_args.config_file
`os.path.expanduser` is gone but not replaced. I get this error
```
~/dev/wazo/wazo-libsccp(WAZO-2818-python-3|✔) % ./buildh makei
usage: buildh [-h] [-p PROFILE] [-c CONFIG_FILE] {make,makei}
buildh: error: argument -c/--config-file: can't open '~/.wazo-libsccp-buildh-config': [Errno 2] No such file or directory: '~/.wazo-libsccp-buildh-config'
~/dev/wazo/wazo-libsccp(WAZO-2818-python-3|✔) % cat ~/.wazo-libsccp-buildh-config 
[default]
host = pcm-dev-primary
directory = wazo-libsccp
```

2022-12-23 13:10 UTC, pc-m commented on buildh
> +    . root@{host}:{directory}
I would not add a user without making it configurable. If someone wants to use `root` or `pcm` they can add the user to there `~/.ssh/config` with the old version

2022-12-23 15:02 UTC, sopelj commented on buildh
> +def command_make(profile: dict):
profile is `dict[str, str]`

2022-12-27 18:37 UTC, DrPyser commented on buildh
> +class CustomConfigParserStorage(collections.UserDict):
I like namespaced names in general, when it helps to understand where things are defined, better describe things in context, how to look up the relevant docs, etc. I use them on a case by case basis, taking into account tradeoff on conciseness. Basic types i import directly from typing for example, there is no value knowing the type comes from a generic typing module. 

Maybe we could agree on clear rules of thumb for these stylistic choices, if there isn't already a mention of this in wazo docs.

2022-12-27 18:51 UTC, sopelj commented on buildh
> +class CustomConfigParserStorage(collections.UserDict):
When it adds clarity and avoids confusion I totally get it, but I don't feel it does. There is no confusion, the script is short and simple, nothing remotely related in name or purpose exists in this repo and it's not some common name in the standard library either. It just means you have to repeat it everywhere it is used and makes lines longer. Not too bad here, but it quickly gets crazy when you have multiple arguments.

Yes, that would be ideal if we can reach an agreement.

2023-01-05 15:08 UTC, DrPyser commented on buildh
> +class CustomConfigParserStorage(collections.UserDict):
Fair enough, in this case conciseness can win.

2023-01-05 15:39 UTC, DrPyser commented on buildh
> +    config = asterisk_parser(config_file)
Removed intermediary asterisk_parser function.

2023-01-06 13:33 UTC, merged